### ISSUE TITLE
Placeholder Conflict %worldguard_region_name%

### ISSUE THREAD

**Issue by ShizenXD** [PlaceholderAPI/WorldGuard-Expansion#26]
Currently, on my server, I'm facing a conflict between two essential plugins: Tab and WordGuard. It seems that the Tab plugin is having difficulty determining which region to prioritize, resulting in a constant and frustrating alternation between the two available regions. This deadlock is negatively impacting the overall functionality of the server. I need to find an effective solution to this problem, either by adjusting the plugins' settings or finding a way to harmonize them to avoid these conflicts.

![unknown_2024 04 01-06 04](https://github.com/PlaceholderAPI/WorldGuard-Expansion/assets/107296268/52fb8a25-e49d-40c9-9064-30721c6e4833)

![image](https://github.com/PlaceholderAPI/WorldGuard-Expansion/assets/107296268/4b1ecc40-ff65-4e81-9fb3-99ef37aa2f97)

**Comment by MackenzieMolloy** [comment]
I cannot seem to replicate this bug on Spigot 26.1.2 with WorldEdit 7.4.3, WorldGuard 7.0.17 and TAB 6.0.3.
<video src="https://github.com/user-attachments/assets/59a23bde-2988-4149-91e5-0b1adaa507ef" width="300" />


I used the following TAB configuration:
```yaml
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  delay-on-join-milliseconds: 0
  scoreboards:
    scoreboard-1.20.3+:
      title: "<#E0B11E>MyServer</#FF0000>"
      display-condition: "%worldguard_region_name%=test"
      lines:
        - "&eTest Region"
    scoreboard:
      title: "<#E0B11E>MyServer</#FF0000>"
      lines:
        - "&7No Region"
```
